server:
  port: 8090

#主数据源
spring:
  shardingsphere:
    datasource:
      #主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:13306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
        username: qcb
        password: 123456
      #从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:13307/test?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
        username: root
        password: 123456
      names: master,slave
    #读写分离
    masterslave:
      load-balance-algorithm-type: round_robin
      name: dataSource
      master-data-source-name: master
      slave-data-source-names: slave
    props:
      sql:
        show: true
